# Generated by Django 5.1.6 on 2025-07-06 10:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_account_last_activity_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staffpermission",
            options={
                "verbose_name": "Staff Permission",
                "verbose_name_plural": "Staff Permissions",
            },
        ),
        migrations.AddField(
            model_name="staffpermission",
            name="can_approve_withdrawals",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staffpermission",
            name="can_manage_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staffpermission",
            name="date_added",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="staffpermission",
            name="last_active",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="staffpermission",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPPORT", "Support Staff"),
                    ("LOAN_OFFICER", "Loan Officer"),
                    ("ACCOUNT_MANAGER", "Account Manager"),
                    ("ADMIN", "System Admin"),
                ],
                default="SUPPORT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="staffpermission",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_permissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="AdminRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_type", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
