# Generated by Django 5.1.6 on 2026-02-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pin_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
