# Generated by Django 5.1.6 on 2025-07-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_transaction_reciever_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanrepayment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("wallet", "Wallet Balance"),
                    ("mobile_money", "Mobile Money"),
                    ("card", "Credit/Debit Card"),
                    ("bank", "Bank Transfer"),
                ],
                default="wallet",
                max_length=20,
            ),
        ),
    ]
