# Generated by Django 5.1.6 on 2025-07-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_loanrepayment_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanrepayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
