# Generated by Django 5.1.6 on 2025-07-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_loanrepayment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="mobilemoneytransaction",
            name="momo_transaction_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="mobilemoneytransaction",
            name="verified_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
